language: cpp
dist: xenial
osx_image: xcode11.3

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-add-repository ppa:beineri/opt-qt-5.14.1-xenial -y;
      sudo add-apt-repository ppa:savoury1/ffmpeg4 -y;
      sudo add-apt-repository ppa:savoury1/graphics -y;
      sudo add-apt-repository ppa:savoury1/multimedia -y;
      sudo apt-get update -q;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install qt514base qt514tools qt514quickcontrols qt514quickcontrols2 qt514graphicaleffects qt514svg qt514imageformats qt514charts-no-lgpl qt514location qt514multimedia -y;
      sudo apt-get install libgl1-mesa-dev libva-dev libvdpau-dev -y;
      sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev libavcodec-dev ffmpeg -y;
      sudo apt-get install libudev-dev libusb-dev -y;
      sudo apt-get install ninja libtool automake m4 -y;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install qt;
      brew install ninja libtool;
      brew install gettext;
      brew link --force gettext;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt514/bin/qt514-env.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/qt/bin:/usr/local/bin; fi
  - cd contribs/; python3 contribs.py; cd ..;
  - qmake --version
  - qmake DEFINES+=USE_CONTRIBS CONFIG+=release PREFIX=/usr

script:
  - make -j$(nproc)

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy_linux.sh -c -p -u; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./deploy_macos.sh -c -p -u; fi
  - echo '>> End of CI build script!';
