language: cpp
dist: xenial

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-add-repository ppa:beineri/opt-qt-5.11.1-xenial -y;
      sudo apt-get update -q;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install qt511base qt511quickcontrols2 qt511svg qt511imageformats qt511tools qt511charts-no-lgpl qt511location qt511multimedia -y;
      sudo apt-get install libgl1-mesa-dev libva-dev libvdpau-dev -y;
      sudo apt-get install libtool automake m4 -y;
      sudo apt-get install libudev-dev libusb-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install qt;
      brew install libtool;
      brew install gettext;
      brew link --force gettext;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt511/bin/qt511-env.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/qt5/bin:/usr/local/bin; fi
  - cd contribs/; python3 contribs.py; cd ..;
  - qmake DEFINES+=USE_CONTRIBS CONFIG+=release PREFIX=/usr

script:
  - make -j$(nproc)

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./deploy_macos.sh; fi
